### ISSUE TITLE
Problem running code

### ISSUE THREAD

**Issue by mak65kma** [petesh/jna-mpr#2]
When running the code in Netbeans on Windows 10 I get the following error:
Found library 'Mpr.dll' at Mpr.dll
Exception in thread "main" com.sun.jna.LastErrorException: [2] The system cannot find the file specified.
        at com.sun.jna.Native.invokeInt(Native Method)
        at com.sun.jna.Function.invoke(Function.java:383)
        at com.sun.jna.Function.invoke(Function.java:315)
        at com.sun.jna.Library$Handler.invoke(Library.java:212)
        at com.sun.proxy.$Proxy0.WNetOpenEnumW(Unknown Source)
        at MprTest.testEnumW(MprTest.java:100)
        at MprTest.main(MprTest.java:125)
Which file is the missing?

**Comment by petesh** [comment]
It's a bug in the implementation - there isn't a missing file; it's just a problem with the calling of the WNetOpenEnumW routine. It'd probably be easier to just take the code from the jna master if you want to have Mpr support.

**Comment by dmigowski** [comment]
You should note that in the Readme! 

But I have to admid that without your sample I wouldn't have been able to use the mpr-code from JNA-platform. Thanks for that.
